version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:current
    steps:
      - checkout
      - run: echo "Hello world!!"
      - sonarcloud/scan
workflows:
  my-workflow:
    jobs:
      - build
